// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260324144355_AddLeetCodeIdToCodingQuestion")]
    partial class AddLeetCodeIdToCodingQuestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.ApplicationHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("JobTrackId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("JobTrackId");

                    b.ToTable("ApplicationHistory");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            JobTrackId = 1,
                            Notes = "Applied via company portal.",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            JobTrackId = 1,
                            Notes = "Recruiter reached out for a technical screen.",
                            Status = 2,
                            UpdatedAt = new DateTime(2025, 10, 8, 9, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            JobTrackId = 2,
                            Notes = "Applied via LinkedIn Easy Apply.",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            JobTrackId = 3,
                            Notes = "Applied through IBM careers page.",
                            Status = 1,
                            UpdatedAt = new DateTime(2025, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("EasyCount")
                        .HasColumnType("int");

                    b.Property<int>("HardCount")
                        .HasColumnType("int");

                    b.Property<int>("MediumCount")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Assessments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompletedAt = new DateTime(2025, 10, 15, 10, 30, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 10, 15, 8, 0, 0, 0, DateTimeKind.Utc),
                            EasyCount = 2,
                            HardCount = 1,
                            MediumCount = 2,
                            Score = 80,
                            StartedAt = new DateTime(2025, 10, 15, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CompletedAt = new DateTime(2025, 11, 1, 9, 45, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 11, 1, 8, 0, 0, 0, DateTimeKind.Utc),
                            EasyCount = 1,
                            HardCount = 0,
                            MediumCount = 2,
                            Score = 75,
                            StartedAt = new DateTime(2025, 11, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 11, 10, 10, 0, 0, 0, DateTimeKind.Utc),
                            EasyCount = 2,
                            HardCount = 0,
                            MediumCount = 1,
                            Score = 0,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.AssessmentQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("int");

                    b.Property<string>("CodeSubmitted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LanguageUsed")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("QuestionId");

                    b.ToTable("AssessmentQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssessmentId = 1,
                            CodeSubmitted = "public int[] TwoSum(int[] nums, int target) { var map = new Dictionary<int,int>(); for(int i=0;i<nums.Length;i++){int c=target-nums[i];if(map.ContainsKey(c))return new[]{map[c],i};map[nums[i]]=i;}return Array.Empty<int>(); }",
                            LanguageUsed = "C#",
                            QuestionId = 1,
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 10, 15, 9, 20, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            AssessmentId = 1,
                            CodeSubmitted = "public ListNode ReverseList(ListNode head){ListNode prev=null,curr=head;while(curr!=null){var next=curr.next;curr.next=prev;prev=curr;curr=next;}return prev;}",
                            LanguageUsed = "C#",
                            QuestionId = 2,
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 10, 15, 9, 50, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            AssessmentId = 1,
                            CodeSubmitted = "// incomplete BFS attempt",
                            LanguageUsed = "C#",
                            QuestionId = 3,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 10, 15, 10, 10, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 4,
                            AssessmentId = 1,
                            CodeSubmitted = "public int LCS(string a,string b){int[,] dp=new int[a.Length+1,b.Length+1];for(int i=1;i<=a.Length;i++)for(int j=1;j<=b.Length;j++)dp[i,j]=a[i-1]==b[j-1]?dp[i-1,j-1]+1:Math.Max(dp[i-1,j],dp[i,j-1]);return dp[a.Length,b.Length];}",
                            LanguageUsed = "C#",
                            QuestionId = 4,
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 10, 15, 10, 25, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 5,
                            AssessmentId = 1,
                            CodeSubmitted = "// naive merge - O(n^2)",
                            LanguageUsed = "C#",
                            QuestionId = 5,
                            Status = 4,
                            SubmittedAt = new DateTime(2025, 10, 15, 10, 28, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 6,
                            AssessmentId = 2,
                            CodeSubmitted = "def twoSum(nums, target):\n    m={}\n    for i,n in enumerate(nums):\n        c=target-n\n        if c in m: return [m[c],i]\n        m[n]=i",
                            LanguageUsed = "Python",
                            QuestionId = 1,
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 1, 9, 15, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 7,
                            AssessmentId = 2,
                            CodeSubmitted = "def levelOrder(root):\n    if not root: return []\n    q,res=[root],[]\n    while q:\n        res.append([n.val for n in q])\n        q=[c for n in q for c in[n.left,n.right] if c]\n    return res",
                            LanguageUsed = "Python",
                            QuestionId = 3,
                            Status = 2,
                            SubmittedAt = new DateTime(2025, 11, 1, 9, 35, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 8,
                            AssessmentId = 2,
                            CodeSubmitted = "# wrong dp transitions",
                            LanguageUsed = "Python",
                            QuestionId = 4,
                            Status = 3,
                            SubmittedAt = new DateTime(2025, 11, 1, 9, 43, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.CodingQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Difficulty")
                        .HasColumnType("int");

                    b.Property<string>("ExampleInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExampleOutput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LeetcodeId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TitleSlug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("TopicId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeetcodeId")
                        .IsUnique();

                    b.HasIndex("TopicId");

                    b.ToTable("CodingQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Given an array of integers and a target, return the indices of two numbers that add up to the target.",
                            Difficulty = 1,
                            ExampleInput = "nums = [2,7,11,15], target = 9",
                            ExampleOutput = "[0,1]",
                            LeetcodeId = 1,
                            Title = "Two Sum",
                            TitleSlug = "two-sum",
                            TopicId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "Reverse a singly linked list iteratively.",
                            Difficulty = 1,
                            ExampleInput = "1 -> 2 -> 3 -> 4 -> 5",
                            ExampleOutput = "5 -> 4 -> 3 -> 2 -> 1",
                            LeetcodeId = 206,
                            Title = "Reverse a Linked List",
                            TitleSlug = "reverse-linked-list",
                            TopicId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Return the level-order (BFS) traversal of a binary tree's node values as a list of lists.",
                            Difficulty = 2,
                            ExampleInput = "[3,9,20,null,null,15,7]",
                            ExampleOutput = "[[3],[9,20],[15,7]]",
                            LeetcodeId = 102,
                            Title = "Binary Tree Level Order Traversal",
                            TitleSlug = "binary-tree-level-order-traversal",
                            TopicId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Given two strings, return the length of their longest common subsequence.",
                            Difficulty = 2,
                            ExampleInput = "text1 = \"abcde\", text2 = \"ace\"",
                            ExampleOutput = "3",
                            LeetcodeId = 11143,
                            Title = "Longest Common Subsequence",
                            TitleSlug = "longest-common-subsequence",
                            TopicId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "Merge k sorted arrays into one sorted array efficiently.",
                            Difficulty = 3,
                            ExampleInput = "[[1,4,7],[2,5,8],[3,6,9]]",
                            ExampleOutput = "[1,2,3,4,5,6,7,8,9]",
                            LeetcodeId = 23,
                            Title = "Merge K Sorted Arrays",
                            TitleSlug = "merge-k-sorted-lists",
                            TopicId = 5
                        });
                });

            modelBuilder.Entity("Domain.Entities.CvJobAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("JobId");

                    b.HasIndex("UserId");

                    b.ToTable("CvJobAnalyses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CvId = 1,
                            Feedback = "Strong match. CV highlights C# and SQL Server experience well. Consider adding cloud certifications to strengthen the Azure requirement.",
                            JobId = 1,
                            Score = 88,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CvId = 2,
                            Feedback = "Excellent frontend skills. Portfolio projects with React and TypeScript are directly relevant. Minor gap: no fintech domain experience mentioned.",
                            JobId = 2,
                            Score = 92,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CvId = 3,
                            Feedback = "Good Python skills shown. Azure experience is limited to internship level; obtaining an AZ-900 certification would significantly improve this application.",
                            JobId = 3,
                            Score = 70,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.HrQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ModelAnswer")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("HrQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ModelAnswer = "Give a concise professional summary: current role, key skills, relevant experience, and why you are excited about this opportunity.",
                            Question = "Tell me about yourself."
                        },
                        new
                        {
                            Id = 2,
                            ModelAnswer = "Pick one strength directly relevant to the role, back it up with a concrete example, and tie it to the value you will bring.",
                            Question = "What is your greatest strength?"
                        },
                        new
                        {
                            Id = 3,
                            ModelAnswer = "Use the STAR method: describe the Situation, your Task, the Actions you took, and the positive Result.",
                            Question = "Describe a challenging situation and how you resolved it."
                        },
                        new
                        {
                            Id = 4,
                            ModelAnswer = "Show ambition that aligns with the company's growth: mention skills you want to develop and how the role fits your long-term career path.",
                            Question = "Where do you see yourself in five years?"
                        },
                        new
                        {
                            Id = 5,
                            ModelAnswer = "Reference specific products, culture, or mission that genuinely excites you.",
                            Question = "Why do you want to work here?"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Interview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Interviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndedAt = new DateTime(2025, 10, 20, 14, 30, 0, 0, DateTimeKind.Utc),
                            Score = 85,
                            StartedAt = new DateTime(2025, 10, 20, 14, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            EndedAt = new DateTime(2025, 11, 5, 11, 25, 0, 0, DateTimeKind.Utc),
                            Score = 90,
                            StartedAt = new DateTime(2025, 11, 5, 11, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Score = 0,
                            StartedAt = new DateTime(2025, 11, 12, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.InterviewQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("InterviewId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("UserResponse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InterviewId");

                    b.HasIndex("QuestionId");

                    b.ToTable("InterviewQuestions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Feedback = "Good structure. Consider mentioning specific measurable achievements next time.",
                            InterviewId = 1,
                            QuestionId = 1,
                            UserResponse = "I am a backend developer with 3 years of experience in .NET. I enjoy solving complex system design problems and have recently been focusing on microservices."
                        },
                        new
                        {
                            Id = 2,
                            Feedback = "Excellent use of a concrete metric. Very compelling answer.",
                            InterviewId = 1,
                            QuestionId = 2,
                            UserResponse = "My greatest strength is analytical thinking. For example, I reduced an API response time by 40% by profiling and refactoring the query layer."
                        },
                        new
                        {
                            Id = 3,
                            Feedback = "STAR method used well. Could elaborate more on the team collaboration aspect.",
                            InterviewId = 1,
                            QuestionId = 3,
                            UserResponse = "I worked at a startup where a production bug caused downtime. I isolated the issue, deployed a hotfix, and then added regression tests to prevent recurrence."
                        },
                        new
                        {
                            Id = 4,
                            Feedback = "Clear and confident. Good mention of soft skills.",
                            InterviewId = 2,
                            QuestionId = 1,
                            UserResponse = "I am a frontend engineer specialising in React. I love building accessible, performant UIs and collaborating closely with designers."
                        },
                        new
                        {
                            Id = 5,
                            Feedback = "Ambitious and realistic. Well aligned with a growth-oriented company.",
                            InterviewId = 2,
                            QuestionId = 4,
                            UserResponse = "In five years I want to be a senior engineer leading the frontend architecture at a product company, mentoring junior developers."
                        },
                        new
                        {
                            Id = 6,
                            InterviewId = 3,
                            QuestionId = 1,
                            UserResponse = "I am a data engineering student interested in cloud pipelines and big data processing."
                        });
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CvId")
                        .HasColumnType("int");

                    b.Property<string>("Info")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CvId");

                    b.HasIndex("UserId");

                    b.ToTable("Jobs", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CvId = 1,
                            Info = "Build scalable microservices using .NET 9 and Azure.",
                            Title = "Senior .NET Developer",
                            Type = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            CvId = 2,
                            Info = "React / TypeScript SPA development for a fintech platform.",
                            Title = "Frontend Engineer",
                            Type = 3,
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            CvId = 3,
                            Info = "Python-based ETL pipelines on Azure Data Factory.",
                            Title = "Data Engineer",
                            Type = 1,
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.Property<int>("JobTrackId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredLevel")
                        .HasColumnType("int");

                    b.HasKey("JobTrackId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("JobSkills");

                    b.HasData(
                        new
                        {
                            JobTrackId = 1,
                            SkillId = 1,
                            RequiredLevel = 3
                        },
                        new
                        {
                            JobTrackId = 1,
                            SkillId = 2,
                            RequiredLevel = 3
                        },
                        new
                        {
                            JobTrackId = 1,
                            SkillId = 3,
                            RequiredLevel = 2
                        },
                        new
                        {
                            JobTrackId = 1,
                            SkillId = 6,
                            RequiredLevel = 1
                        },
                        new
                        {
                            JobTrackId = 2,
                            SkillId = 4,
                            RequiredLevel = 3
                        },
                        new
                        {
                            JobTrackId = 2,
                            SkillId = 9,
                            RequiredLevel = 2
                        },
                        new
                        {
                            JobTrackId = 3,
                            SkillId = 5,
                            RequiredLevel = 2
                        },
                        new
                        {
                            JobTrackId = 3,
                            SkillId = 10,
                            RequiredLevel = 2
                        });
                });

            modelBuilder.Entity("Domain.Entities.JobTrack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("CurrentStatus")
                        .HasColumnType("int");

                    b.Property<int>("JobId")
                        .HasColumnType("int");

                    b.Property<string>("JobUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Location")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("JobId")
                        .IsUnique();

                    b.ToTable("JobTracks", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppliedAt = new DateTime(2025, 10, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            CompanyName = "Microsoft Egypt",
                            CurrentStatus = 2,
                            JobId = 1,
                            JobUrl = "https://careers.microsoft.com/job/1",
                            Location = "Cairo, Egypt",
                            Salary = 25000.00m
                        },
                        new
                        {
                            Id = 2,
                            AppliedAt = new DateTime(2025, 10, 5, 10, 0, 0, 0, DateTimeKind.Utc),
                            CompanyName = "Noon",
                            CurrentStatus = 1,
                            JobId = 2,
                            JobUrl = "https://jobs.noon.com/job/2",
                            Location = "Dubai, UAE",
                            Salary = 18000.00m
                        },
                        new
                        {
                            Id = 3,
                            AppliedAt = new DateTime(2025, 10, 10, 9, 0, 0, 0, DateTimeKind.Utc),
                            CompanyName = "IBM Egypt",
                            CurrentStatus = 1,
                            JobId = 3,
                            JobUrl = "https://careers.ibm.com/job/3",
                            Location = "Cairo, Egypt",
                            Salary = 20000.00m
                        });
                });

            modelBuilder.Entity("Domain.Entities.QuestionTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("QuestionTopics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Arrays & Strings"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Linked Lists"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Trees & Graphs"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dynamic Programming"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sorting & Searching"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ASP.NET Core"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SQL Server"
                        },
                        new
                        {
                            Id = 4,
                            Name = "React"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Python"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Docker"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Git"
                        },
                        new
                        {
                            Id = 8,
                            Name = "JavaScript"
                        },
                        new
                        {
                            Id = 9,
                            Name = "TypeScript"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Azure"
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("JoinDate")
                        .HasColumnType("date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("PasswordHashed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Cairo, Egypt",
                            Email = "admin@launchpad.io",
                            FirstName = "Admin",
                            IsActive = true,
                            JoinDate = new DateOnly(2024, 1, 1),
                            LastName = "LaunchPad",
                            PasswordHashed = "$2a$11$REPLACE_WITH_REAL_BCRYPT_HASH_ADMIN",
                            PhoneNumber = "01000000000",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            Address = "Giza, Egypt",
                            Email = "ahmed.hassan@example.com",
                            FirstName = "Ahmed",
                            IsActive = true,
                            JoinDate = new DateOnly(2025, 3, 10),
                            LastName = "Hassan",
                            PasswordHashed = "$2a$11$REPLACE_WITH_REAL_BCRYPT_HASH_AHMED",
                            PhoneNumber = "01012345678",
                            Role = 1
                        },
                        new
                        {
                            Id = 3,
                            Address = "Alexandria, Egypt",
                            Email = "sara.ali@example.com",
                            FirstName = "Sara",
                            IsActive = true,
                            JoinDate = new DateOnly(2025, 6, 1),
                            LastName = "Ali",
                            PasswordHashed = "$2a$11$REPLACE_WITH_REAL_BCRYPT_HASH_SARA",
                            PhoneNumber = "01123456789",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            Address = "Mansoura, Egypt",
                            Email = "omar.khaled@example.com",
                            FirstName = "Omar",
                            IsActive = true,
                            JoinDate = new DateOnly(2025, 9, 15),
                            LastName = "Khaled",
                            PasswordHashed = "$2a$11$REPLACE_WITH_REAL_BCRYPT_HASH_OMAR",
                            PhoneNumber = "01234567890",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserCv", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserCvs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileName = "ahmed_hassan_cv.pdf",
                            FilePath = "cvs/2/ahmed_hassan_cv.pdf",
                            IsDefault = true,
                            Score = 82,
                            UploadedAt = new DateTime(2025, 3, 11, 10, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            FileName = "sara_ali_cv.pdf",
                            FilePath = "cvs/3/sara_ali_cv.pdf",
                            IsDefault = true,
                            Score = 91,
                            UploadedAt = new DateTime(2025, 6, 2, 9, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            FileName = "omar_khaled_cv.pdf",
                            FilePath = "cvs/4/omar_khaled_cv.pdf",
                            IsDefault = true,
                            Score = 74,
                            UploadedAt = new DateTime(2025, 9, 16, 8, 0, 0, 0, DateTimeKind.Utc),
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserEducation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Degree")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<string>("Grade")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("University")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserEducations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Degree = "Bachelor's",
                            EndDate = new DateOnly(2022, 6, 30),
                            Grade = "A",
                            Program = "Computer Science",
                            StartDate = new DateOnly(2018, 9, 1),
                            University = "Cairo University",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Degree = "Bachelor's",
                            EndDate = new DateOnly(2023, 6, 30),
                            Grade = "A+",
                            Program = "Software Engineering",
                            StartDate = new DateOnly(2019, 9, 1),
                            University = "Ain Shams University",
                            UserId = 3
                        },
                        new
                        {
                            Id = 3,
                            Degree = "Bachelor's",
                            EndDate = new DateOnly(2024, 6, 30),
                            Grade = "B+",
                            Program = "Information Technology",
                            StartDate = new DateOnly(2020, 9, 1),
                            University = "Mansoura University",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Company")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserExperiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Company = "Vodafone Egypt",
                            Description = "Built and maintained RESTful APIs using ASP.NET Core and SQL Server.",
                            EndDate = new DateOnly(2024, 12, 31),
                            StartDate = new DateOnly(2022, 7, 1),
                            Title = "Backend Developer",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Company = "Freelance",
                            Description = "Delivered web applications for local SMEs using .NET and React.",
                            EndDate = new DateOnly(2022, 6, 30),
                            StartDate = new DateOnly(2021, 1, 1),
                            Title = "Full-Stack Developer",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Company = "Swvl",
                            Description = "Developed user-facing features with React and TypeScript in an agile team.",
                            StartDate = new DateOnly(2023, 3, 1),
                            Title = "Frontend Developer",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Company = "Instabug",
                            Description = "Built ETL pipelines with Python and managed cloud infrastructure on Azure.",
                            EndDate = new DateOnly(2024, 9, 30),
                            StartDate = new DateOnly(2024, 6, 1),
                            Title = "Data Engineer Intern",
                            UserId = 4
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserSkill", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.HasKey("UserId", "SkillId");

                    b.HasIndex("SkillId");

                    b.ToTable("UserSkills");

                    b.HasData(
                        new
                        {
                            UserId = 2,
                            SkillId = 1,
                            Level = 3
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 2,
                            Level = 2
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 3,
                            Level = 2
                        },
                        new
                        {
                            UserId = 2,
                            SkillId = 7,
                            Level = 2
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 4,
                            Level = 3
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 8,
                            Level = 3
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 9,
                            Level = 2
                        },
                        new
                        {
                            UserId = 3,
                            SkillId = 7,
                            Level = 1
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 5,
                            Level = 2
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 6,
                            Level = 1
                        },
                        new
                        {
                            UserId = 4,
                            SkillId = 10,
                            Level = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.ApplicationHistory", b =>
                {
                    b.HasOne("Domain.Entities.JobTrack", "JobTrack")
                        .WithMany("History")
                        .HasForeignKey("JobTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTrack");
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Assessments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.AssessmentQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Assessment", "Assessment")
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CodingQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.CodingQuestion", b =>
                {
                    b.HasOne("Domain.Entities.QuestionTopic", "Topic")
                        .WithMany("Questions")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.Entities.CvJobAnalysis", b =>
                {
                    b.HasOne("Domain.Entities.UserCv", "Cv")
                        .WithMany("CvJobAnalyses")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithMany("CvJobAnalyses")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("CvJobAnalyses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("Job");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Interview", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Interviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.InterviewQuestion", b =>
                {
                    b.HasOne("Domain.Entities.Interview", "Interview")
                        .WithMany("InterviewQuestions")
                        .HasForeignKey("InterviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.HrQuestion", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Interview");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.HasOne("Domain.Entities.UserCv", "Cv")
                        .WithMany("Jobs")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Jobs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cv");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.JobSkill", b =>
                {
                    b.HasOne("Domain.Entities.JobTrack", "JobTrack")
                        .WithMany("SkillsRequired")
                        .HasForeignKey("JobTrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany("JobSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobTrack");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("Domain.Entities.JobTrack", b =>
                {
                    b.HasOne("Domain.Entities.Job", "Job")
                        .WithOne("JobTrack")
                        .HasForeignKey("Domain.Entities.JobTrack", "JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("Domain.Entities.UserCv", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Cvs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserEducation", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Educations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserExperience", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Experiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.UserSkill", b =>
                {
                    b.HasOne("Domain.Entities.Skill", "Skill")
                        .WithMany("UserSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserSkills")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Assessment", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Interview", b =>
                {
                    b.Navigation("InterviewQuestions");
                });

            modelBuilder.Entity("Domain.Entities.Job", b =>
                {
                    b.Navigation("CvJobAnalyses");

                    b.Navigation("JobTrack");
                });

            modelBuilder.Entity("Domain.Entities.JobTrack", b =>
                {
                    b.Navigation("History");

                    b.Navigation("SkillsRequired");
                });

            modelBuilder.Entity("Domain.Entities.QuestionTopic", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("Domain.Entities.Skill", b =>
                {
                    b.Navigation("JobSkills");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("CvJobAnalyses");

                    b.Navigation("Cvs");

                    b.Navigation("Educations");

                    b.Navigation("Experiences");

                    b.Navigation("Interviews");

                    b.Navigation("Jobs");

                    b.Navigation("UserSkills");
                });

            modelBuilder.Entity("Domain.Entities.UserCv", b =>
                {
                    b.Navigation("CvJobAnalyses");

                    b.Navigation("Jobs");
                });
#pragma warning restore 612, 618
        }
    }
}
